-- Auto-generated from assets/<test-*>/test.json + seed/seed-config.json
-- DO NOT EDIT BY HAND (edit config/JSON, then re-run: node scripts/generate_d1_seed.cjs)

PRAGMA foreign_keys = ON;

DELETE FROM tests;

-- test: test-root-vegetables
INSERT INTO tests (test_id, title, description_json, author, author_img_path, thumbnail_path, source_path, tags_json, question_count, is_published, created_at, updated_at) VALUES ( 'test-root-vegetables', '뿌리채소 성향 테스트', '["뿌리뿌리 뿌리채소 유형 ✨","뿌리채소 농장에서 친구들 이끌고 신나게 돌아다니고 싶은지,","혼자 조용히 뿌리채소의 질감을 음미하고 싶은지… 👀","이런 당신의 뿌리채소 스타일로","MBTI 성격 유형을 살짝 들여다봐요 💕","몇 가지 질문에 답하면","✔️ 당신이 어떤 뿌리채소 취향을 더 좋아하는지","✔️ 어떤 포인트에 끌리는 타입인지","귀여운 뿌리채소·캐릭터 해설과 함께","콕콕 알려드릴게요 🥔🍠🥕🧅🌰"]', '라푸', 'assets/test-root-vegetables/images/author.png', 'assets/test-root-vegetables/images/thumbnail.png', 'test-root-vegetables/test.json', '["뿌리채소","캐릭터","MBTI"]', 12, 1, '2025-12-26', '2025-12-26' );

INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/author.png', 'author', 'author', 'image/png', 10506, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ENFJ.png', 'result', 'ENFJ', 'image/png', 836921, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ENFP.png', 'result', 'ENFP', 'image/png', 813788, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ENTJ.png', 'result', 'ENTJ', 'image/png', 1425856, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ENTP.png', 'result', 'ENTP', 'image/png', 488604, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ESFJ.png', 'result', 'ESFJ', 'image/png', 571142, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ESFP.png', 'result', 'ESFP', 'image/png', 713283, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ESTJ.png', 'result', 'ESTJ', 'image/png', 1275359, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ESTP.png', 'result', 'ESTP', 'image/png', 763550, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/INFJ.png', 'result', 'INFJ', 'image/png', 823828, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/INFP.png', 'result', 'INFP', 'image/png', 972445, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/INTJ.png', 'result', 'INTJ', 'image/png', 741017, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/INTP.png', 'result', 'INTP', 'image/png', 559688, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ISFJ.png', 'result', 'ISFJ', 'image/png', 2270239, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ISFP.png', 'result', 'ISFP', 'image/png', 660405, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ISTJ.png', 'result', 'ISTJ', 'image/png', 1107093, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/ISTP.png', 'result', 'ISTP', 'image/png', 1958190, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q1.png', 'question', 'Q1', 'image/png', 466484, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q10.png', 'question', 'Q10', 'image/png', 432848, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q11.png', 'question', 'Q11', 'image/png', 445411, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q12.png', 'question', 'Q12', 'image/png', 436233, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q2.png', 'question', 'Q2', 'image/png', 449688, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q3.png', 'question', 'Q3', 'image/png', 447264, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q4.png', 'question', 'Q4', 'image/png', 475154, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q5.png', 'question', 'Q5', 'image/png', 484612, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q6.png', 'question', 'Q6', 'image/png', 441493, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q7.png', 'question', 'Q7', 'image/png', 454661, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q8.png', 'question', 'Q8', 'image/png', 444566, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/Q9.png', 'question', 'Q9', 'image/png', 457200, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-root-vegetables', 'assets/test-root-vegetables/images/thumbnail.png', 'thumbnail', 'thumbnail', 'image/png', 725512, '2025-01-01T00:00:00.000Z' );

-- test: test-summer
INSERT INTO tests (test_id, title, description_json, author, author_img_path, thumbnail_path, source_path, tags_json, question_count, is_published, created_at, updated_at) VALUES ( 'test-summer', '여름 바캉스 스타일 테스트', '["두근두근 여름방학 유형 ✨","여름방학에 친구들이랑 미친 듯이 놀고 싶은지,","혼자 조용히 책 읽으며 쉬고 싶은지… 👀","이런 당신의 방학 스타일로","성격 유형을 살짝 들여다봐요 💕","몇 가지 질문에 답하면","✔️ 당신이 어떤 방학 계획을 더 좋아하는지","✔️ 어떤 포인트에 끌리는 타입인지","귀여운 동물·캐릭터 해설과 함께","콕콕 알려드릴게요 🐰🦉🦔🦥🦩"]', '우애앵애', 'assets/test-summer/images/author.png', 'assets/test-summer/images/thumbnail.png', 'test-summer/test.json', '["여름","여행","휴가","바캉스"]', 12, 1, '2025-12-08', '2025-12-08' );

INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/author.png', 'author', 'author', 'image/png', 22237, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ENFJ.png', 'result', 'ENFJ', 'image/png', 186940, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ENFP.png', 'result', 'ENFP', 'image/png', 318360, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ENTJ.png', 'result', 'ENTJ', 'image/png', 302455, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ENTP.png', 'result', 'ENTP', 'image/png', 276024, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ESFJ.png', 'result', 'ESFJ', 'image/png', 382818, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ESFP.png', 'result', 'ESFP', 'image/png', 332347, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ESTJ.png', 'result', 'ESTJ', 'image/png', 287302, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ESTP.png', 'result', 'ESTP', 'image/png', 405687, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/INFJ.png', 'result', 'INFJ', 'image/png', 366348, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/INFP.png', 'result', 'INFP', 'image/png', 454715, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/INTJ.png', 'result', 'INTJ', 'image/png', 271971, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/INTP.png', 'result', 'INTP', 'image/png', 260326, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ISFJ.png', 'result', 'ISFJ', 'image/png', 345771, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ISFP.png', 'result', 'ISFP', 'image/png', 461057, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ISTJ.png', 'result', 'ISTJ', 'image/png', 456563, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/ISTP.png', 'result', 'ISTP', 'image/png', 319179, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q1.png', 'question', 'Q1', 'image/png', 432694, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q10.png', 'question', 'Q10', 'image/png', 432340, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q11.png', 'question', 'Q11', 'image/png', 388722, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q12.png', 'question', 'Q12', 'image/png', 442139, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q2.png', 'question', 'Q2', 'image/png', 444669, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q3.png', 'question', 'Q3', 'image/png', 429249, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q4.png', 'question', 'Q4', 'image/png', 446750, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q5.png', 'question', 'Q5', 'image/png', 431830, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q6.png', 'question', 'Q6', 'image/png', 407874, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q7.png', 'question', 'Q7', 'image/png', 398448, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q8.png', 'question', 'Q8', 'image/png', 435297, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/Q9.png', 'question', 'Q9', 'image/png', 399517, '2025-01-01T00:00:00.000Z' );
INSERT INTO test_images (test_id, image_key, image_type, image_name, content_type, size_bytes, uploaded_at) VALUES ( 'test-summer', 'assets/test-summer/images/thumbnail.png', 'thumbnail', 'thumbnail', 'image/png', 1213844, '2025-01-01T00:00:00.000Z' );
